// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BodeTrack.Entities.Entities;

public partial class tbArticulos
{
    public int Arti_Id { get; set; }

    public string Arti_Codigo { get; set; }

    public string Arti_CodigoBarras { get; set; }

    public string Arti_Descripcion { get; set; }

    public bool Arti_Estado { get; set; }

    public int Arti_Creacion { get; set; }

    public DateTime Arti_FechaCreacion { get; set; }

    public int? Arti_Modificacion { get; set; }

    public DateTime? Arti_FechaModificacion { get; set; }

}