// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BodeTrack.Entities.Entities;

public partial class tbCargos
{
    public int Carg_Id { get; set; }

    public string Carg_Descripcion { get; set; }

    public bool Carg_Estado { get; set; }

    public int Carg_Creacion { get; set; }

    public DateTime Carg_FechaCreacion { get; set; }

    public int? Carg_Modificacion { get; set; }

    public DateTime? Carg_FechaModificacion { get; set; }

    [NotMapped]
    public string Usua_Creacion { get; set; }

    [NotMapped]
    public string Usua_Modificacion { get; set; }



}