// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BodeTrack.Entities.Entities;

public partial class tbDepartamentos
{
    public string Dept_Codigo { get; set; }

    public string Dept_Descripcion { get; set; }

    public bool Dept_Estado { get; set; }

    public int Dept_Creacion { get; set; }

    public DateTime Dept_FechaCreacion { get; set; }

    public int? Dept_Modificacion { get; set; }

    public DateTime? Dept_FechaModificacion { get; set; }
}