// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BodeTrack.Entities.Entities;

public partial class tbEntradasDetalle
{
    public int Ende_Id { get; set; }

    public int Entr_Id { get; set; }

    public int Arti_Id { get; set; }

    public int Ende_Cantidad { get; set; }

    public decimal Ende_CostoUnitario { get; set; }

    public string Ende_LoteCodigo { get; set; }

    public DateOnly Ende_FechaVencimiento { get; set; }

    public DateOnly Ende_FechaFabricacion { get; set; }

    public bool Ende_Estado { get; set; }

    public int Ende_Creacion { get; set; }

    public DateTime Ende_FechaCreacion { get; set; }

    public int? Ende_Modificacion { get; set; }

    public DateTime? Ende_FechaModificacion { get; set; }

    public virtual tbArticulos Arti { get; set; }

    public virtual tbUsuarios Ende_CreacionNavigation { get; set; }

    public virtual tbUsuarios Ende_ModificacionNavigation { get; set; }

    public virtual tbEntradas Entr { get; set; }
}