// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BodeTrack.Entities.Entities;

public partial class tbEntradas
{
    public int Entr_Id { get; set; }

    public string Entr_NumeroFactura { get; set; }

    public DateTime Entr_FechaEntrada { get; set; }

    public string Entr_Observacion { get; set; }

    public bool Entr_Estado { get; set; }

    public int Entr_Creacion { get; set; }

    public DateTime Entr_FechaCreacion { get; set; }

    public int? Entr_Modificacion { get; set; }

    public DateTime? Entr_FechaModificacion { get; set; }

    [NotMapped]
    public string Usua_Creacion { get; set; }

    [NotMapped]
    public string Usua_Modificacion { get; set; }
}