// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BodeTrack.Entities.Entities;

public partial class tbEstadosCiviles
{
    public int EsCi_Id { get; set; }

    public string EsCi_Descripcion { get; set; }

    public bool EsCi_Estado { get; set; }

    public int EsCi_Creacion { get; set; }

    public DateTime EsCi_FechaCreacion { get; set; }

    public int? EsCi_Modificacion { get; set; }

    public DateTime? EsCi_FechaModificacion { get; set; }
}