// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BodeTrack.Entities.Entities;

public partial class tbSalidasDetalle
{
    public int Sade_Id { get; set; }

    public int Sali_Id { get; set; }

    public int Arti_Id { get; set; }

    public int Lote_Id { get; set; }

    public int Sade_Cantidad { get; set; }

    public decimal Sade_CostoUnitario { get; set; }

    public DateOnly Sade_FechaVencimiento { get; set; }

    public bool Sade_Estado { get; set; }

    public int Sade_Creacion { get; set; }

    public DateTime Sade_FechaCreacion { get; set; }

    public int? Sade_Modificacion { get; set; }

    public DateTime? Sade_FechaModificacion { get; set; }


}