// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BodeTrack.Entities.Entities;

public partial class tbSalidas
{
    public int Sali_Id { get; set; }

    public int Sucs_Id { get; set; }

    public DateTime Sali_FechaSalida { get; set; }

    public string Sali_EstadoSalida { get; set; }

    public decimal Sali_CostoTotal { get; set; }

    public int Sali_UsuarioEnvia { get; set; }

    public int? Sali_UsuarioRecibe { get; set; }

    public int? Vehi_Id { get; set; }

    public int? Sali_Transportista { get; set; }

    public DateTime? Sali_FechaRecepcion { get; set; }

    public string Sali_GuiaRemision { get; set; }

    public bool Sali_Estado { get; set; }

    public int Sali_Creacion { get; set; }

    public DateTime Sali_FechaCreacion { get; set; }

    public int? Sali_Modificacion { get; set; }

    public DateTime? Sali_FechaModificacion { get; set; }

    // Campos del SP_Salidas_Listar
    [NotMapped]
    public int Secuencia { get; set; }

    [NotMapped]
    public string SucursalDestino { get; set; }

    [NotMapped]
    public int UnidadesTotales { get; set; }

    [NotMapped]
    public string UsuarioEnvia { get; set; }

    [NotMapped]
    public string UsuarioRecibe { get; set; }

    [NotMapped]
    public string Usua_Creacion { get; set; }

    [NotMapped]
    public string Usua_Modificacion { get; set; }

    // Campos adicionales del SP_Salida_ObtenerCompleta
    [NotMapped]
    public int Code_Status { get; set; }

    [NotMapped]
    public string Message_Status { get; set; }

    [NotMapped]
    public string Vehiculo { get; set; }

    [NotMapped]
    public string Transportista { get; set; }

    [NotMapped]
    public string DetalleSalida { get; set; } // JSON string - se deserializa en frontend

    [NotMapped]
    public string UsuaCreacionNombre { get; set; }

    [NotMapped]
    public string UsuaModificacionNombre { get; set; }
}