// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BodeTrack.Entities.Entities;

public partial class tbSucursales
{
    public int Sucs_Id { get; set; }

    public string Sucs_Descripcion { get; set; }

    public string Muni_Codigo { get; set; }

    public bool Sucs_Estado { get; set; }

    public int Sucs_Creacion { get; set; }

    public DateTime Sucs_FechaCreacion { get; set; }

    public int? Sucs_Modificacion { get; set; }

    public DateTime? Sucs_FechaModificacion { get; set; }

    public virtual tbMunicipios Muni_CodigoNavigation { get; set; }

    public virtual tbUsuarios Sucs_CreacionNavigation { get; set; }

    public virtual tbUsuarios Sucs_ModificacionNavigation { get; set; }

    public virtual ICollection<tbSalidas> tbSalidas { get; set; } = new List<tbSalidas>();
}