// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BodeTrack.Entities.Entities;

public partial class tbUsuarios
{
    // === Campos propios de tbUsuarios (mapeados a la tabla) ===
    public int Usua_Id { get; set; }
    public string Usua_NombreUsuario { get; set; } = null!;
    public string Usua_Clave { get; set; } = null!;
    public bool Usua_EsAdmin { get; set; }
    public int Empl_Id { get; set; }
    public bool Usua_Estado { get; set; }
    public int Usua_Creacion { get; set; }
    public DateTime Usua_FechaCreacion { get; set; }
    public int? Usua_Modificacion { get; set; }
    public DateTime? Usua_FechaModificacion { get; set; }

    [NotMapped]
    public bool Empl_EsJefeBodega { get; set; }

    [NotMapped]
    public string Empl_Nombres { get; set; } = null!;

    [NotMapped]
    public string Empl_Apellidos { get; set; } = null!;

    [NotMapped]
    public string Empl_DNI { get; set; } = null!;

    [NotMapped]
    public string Empl_Sexo { get; set; } = null!;

    [NotMapped]
    public string Empl_Cargo { get; set; } = null;

    [NotMapped]
    public int Sucs_Id { get; set; }

    [NotMapped]
    public string Sucs_Descripcion { get; set; } = null!;

    [NotMapped]
    public string Empl_EstadoCivil { get; set; } = null!;

    [NotMapped]
    public string Empl_Municipio { get; set; } = null!;

    [NotMapped]
    public string Empl_Departamento { get; set; } = null!;

    [NotMapped]
    public int Code_Status { get; set; }

    [NotMapped]
    public string? Message_Status { get; set; }
}