// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BodeTrack.Entities.Entities;

public partial class tbVehiculos
{
    public int Vehi_Id { get; set; }

    public string Vehi_Codigo { get; set; }

    public string Vehi_Marca { get; set; }

    public string Vehi_Modelo { get; set; }

    public string Vehi_Placa { get; set; }

    public int Vehi_Anio { get; set; }

    public bool Vehi_Estado { get; set; }

    public int Vehi_Creacion { get; set; }

    public DateTime Vehi_FechaCreacion { get; set; }

    public int? Vehi_Modificacion { get; set; }

    public DateTime? Vehi_FechaModificacion { get; set; }

    public virtual tbUsuarios Vehi_CreacionNavigation { get; set; }

    public virtual tbUsuarios Vehi_ModificacionNavigation { get; set; }

    public virtual ICollection<tbSalidas> tbSalidas { get; set; } = new List<tbSalidas>();
}