// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BodeTrack.Entities.Entities;
using Microsoft.EntityFrameworkCore;

namespace BodeTrack.DataAccess.Context;

public partial class database_bodetrackContext : DbContext
{
    public database_bodetrackContext(DbContextOptions<database_bodetrackContext> options)
        : base(options)
    {
    }

    public database_bodetrackContext()
    {
    }

    public virtual DbSet<tbArticulos> tbArticulos { get; set; }

    public virtual DbSet<tbCargos> tbCargos { get; set; }

    public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }

    public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }

    public virtual DbSet<tbEntradas> tbEntradas { get; set; }

    public virtual DbSet<tbEntradasDetalle> tbEntradasDetalle { get; set; }

    public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }

    public virtual DbSet<tbLotes> tbLotes { get; set; }

    public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }

    public virtual DbSet<tbSalidas> tbSalidas { get; set; }

    public virtual DbSet<tbSalidasDetalle> tbSalidasDetalle { get; set; }

    public virtual DbSet<tbSucursales> tbSucursales { get; set; }

    public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }

    public virtual DbSet<tbVehiculos> tbVehiculos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Modern_Spanish_CI_AS");

        modelBuilder.Entity<tbArticulos>(entity =>
        {
            entity.HasKey(e => e.Arti_Id).HasName("PK_Gral_tbArticulos_Arti_Id");

            entity.ToTable("tbArticulos", "Gral");

            entity.HasIndex(e => e.Arti_Codigo, "UQ__tbArticu__5D6CE6995875DCAB").IsUnique();

            entity.Property(e => e.Arti_Codigo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Arti_CodigoBarras)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Arti_Descripcion)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Arti_Estado).HasDefaultValue(true);
            entity.Property(e => e.Arti_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Arti_FechaModificacion).HasColumnType("datetime");

        });

        modelBuilder.Entity<tbCargos>(entity =>
        {
            entity.HasKey(e => e.Carg_Id).HasName("PK_Gral_tbCargos_Carg_Id");

            entity.ToTable("tbCargos", "Gral");

            entity.Property(e => e.Carg_Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Carg_Estado).HasDefaultValue(true);
            entity.Property(e => e.Carg_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Carg_FechaModificacion).HasColumnType("datetime");


        });

        modelBuilder.Entity<tbDepartamentos>(entity =>
        {
            entity.HasKey(e => e.Dept_Codigo).HasName("PK_Gral_tbDepartamentos_Dept_Codigo");

            entity.ToTable("tbDepartamentos", "Gral");

            entity.Property(e => e.Dept_Codigo)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Dept_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Dept_Estado).HasDefaultValue(true);
            entity.Property(e => e.Dept_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Dept_FechaModificacion).HasColumnType("datetime");

        });

        modelBuilder.Entity<tbEmpleados>(entity =>
        {
            entity.HasKey(e => e.Empl_Id).HasName("PK_Gral_tbEmpleados_Empl_Id");

            entity.ToTable("tbEmpleados", "Gral");

            entity.HasIndex(e => e.Empl_DNI, "UQ__tbEmplea__44CE58E20514D45B").IsUnique();

            entity.Property(e => e.Empl_Apellidos)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Empl_Codigo)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Empl_DNI)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Empl_Direccion)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Empl_Estado).HasDefaultValue(true);
            entity.Property(e => e.Empl_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Empl_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Empl_Nombres)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Empl_Sexo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Muni_Codigo)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);

            
    
        });

        modelBuilder.Entity<tbEntradas>(entity =>
        {
            entity.HasKey(e => e.Entr_Id).HasName("PK_Inve_tbEntradas_Entr_Id");

            entity.ToTable("tbEntradas", "Inve");

            entity.Property(e => e.Entr_Estado).HasDefaultValue(true);
            entity.Property(e => e.Entr_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Entr_FechaEntrada).HasColumnType("datetime");
            entity.Property(e => e.Entr_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Entr_NumeroFactura)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Entr_Observacion)
                .HasMaxLength(250)
                .IsUnicode(false);

        });

        modelBuilder.Entity<tbEntradasDetalle>(entity =>
        {
            entity.HasKey(e => e.Ende_Id).HasName("PK_Inve_tbEntradasDetalle_Ende_Id");

            entity.ToTable("tbEntradasDetalle", "Inve");

            entity.Property(e => e.Ende_CostoUnitario).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Ende_Estado).HasDefaultValue(true);
            entity.Property(e => e.Ende_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Ende_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Ende_LoteCodigo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            

            
        });

        modelBuilder.Entity<tbEstadosCiviles>(entity =>
        {
            entity.HasKey(e => e.EsCi_Id).HasName("PK_Gral_tbEstadosCiviles_EsCi_Id");

            entity.ToTable("tbEstadosCiviles", "Gral");

            entity.Property(e => e.EsCi_Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EsCi_Estado).HasDefaultValue(true);
            entity.Property(e => e.EsCi_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.EsCi_FechaModificacion).HasColumnType("datetime");

        });

        modelBuilder.Entity<tbLotes>(entity =>
        {
            entity.HasKey(e => e.Lote_Id).HasName("PK_Inve_tbLotes_Lote_Id");

            entity.ToTable("tbLotes", "Inve");

            entity.Property(e => e.Lote_Atributo1)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Lote_Atributo2)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Lote_Codigo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Lote_CostoUnitario).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Lote_Estado).HasDefaultValue(true);
            entity.Property(e => e.Lote_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Lote_FechaModificacion).HasColumnType("datetime");

            

        });

        modelBuilder.Entity<tbMunicipios>(entity =>
        {
            entity.HasKey(e => e.Muni_Codigo).HasName("PK_Gral_tbMunicipios_Muni_Codigo");

            entity.ToTable("tbMunicipios", "Gral");

            entity.Property(e => e.Muni_Codigo)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.Dept_Codigo)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Muni_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Muni_Estado).HasDefaultValue(true);
            entity.Property(e => e.Muni_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Muni_FechaModificacion).HasColumnType("datetime");

            

        });

        modelBuilder.Entity<tbSalidas>(entity =>
        {
            entity.HasKey(e => e.Sali_Id).HasName("PK_Inve_tbSalidas_Sali_Id");

            entity.ToTable("tbSalidas", "Inve");

            entity.Property(e => e.Sali_CostoTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Sali_Estado).HasDefaultValue(true);
            entity.Property(e => e.Sali_EstadoSalida)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Sali_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Sali_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Sali_FechaRecepcion).HasColumnType("datetime");
            entity.Property(e => e.Sali_FechaSalida).HasColumnType("datetime");
            entity.Property(e => e.Sali_GuiaRemision)
                .HasMaxLength(100)
                .IsUnicode(false);

            

        });

        modelBuilder.Entity<tbSalidasDetalle>(entity =>
        {
            entity.HasKey(e => e.Sade_Id).HasName("PK_Inve_tbSalidasDetalle_Sade_Id");

            entity.ToTable("tbSalidasDetalle", "Inve");

            entity.Property(e => e.Sade_CostoUnitario).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Sade_Estado).HasDefaultValue(true);
            entity.Property(e => e.Sade_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Sade_FechaModificacion).HasColumnType("datetime");

            

        });

        modelBuilder.Entity<tbSucursales>(entity =>
        {
            entity.HasKey(e => e.Sucs_Id).HasName("PK_Gral_tbSucursales_Sucs_Id");

            entity.ToTable("tbSucursales", "Gral");

            entity.Property(e => e.Muni_Codigo)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.Sucs_Descripcion)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Sucs_Estado).HasDefaultValue(true);
            entity.Property(e => e.Sucs_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Sucs_FechaModificacion).HasColumnType("datetime");

            
        });

        modelBuilder.Entity<tbUsuarios>(entity =>
        {
            entity.HasKey(e => e.Usua_Id).HasName("PK_Acce_tbUsuarios_Usua_Id");

            entity.ToTable("tbUsuarios", "Acce");

            entity.HasIndex(e => e.Usua_NombreUsuario, "UQ__tbUsuari__0703C30E753AD6F5").IsUnique();

            entity.Property(e => e.Usua_Clave)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Usua_Estado).HasDefaultValue(true);
            entity.Property(e => e.Usua_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Usua_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Usua_NombreUsuario)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<tbVehiculos>(entity =>
        {
            entity.HasKey(e => e.Vehi_Id).HasName("PK_Gral_tbVehiculos_Vehi_Id");

            entity.ToTable("tbVehiculos", "Gral");

            entity.HasIndex(e => e.Vehi_Placa, "UQ__tbVehicu__406955E9BE1885F3").IsUnique();

            entity.Property(e => e.Vehi_Codigo)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Vehi_Estado).HasDefaultValue(true);
            entity.Property(e => e.Vehi_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Vehi_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Vehi_Marca)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Vehi_Modelo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Vehi_Placa)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}